keep_files: [assets]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-sass-converter
  - jekyll-relative-links

repository: https://github.com/2sugarcubes/2sugarcubes.github.io

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
